# Site Settings
title: Rae
email: rae.austin.official@gmail.com
description: >
  Adapted main page.
baseurl: 
url: "http://localhost:4000"
github_username:  RaeKobi
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM